const std = @import("std");

pub const ERROR_DOCS_BASE = "https://docs.e2enetworks.com/error-codes#";

pub const ERR_UUIDV7_CANONICAL_FORMAT = "UZ-UUIDV7-003";
pub const ERR_UUIDV7_ID_GENERATION_FAILED = "UZ-UUIDV7-005";
pub const ERR_UUIDV7_INVALID_ID_SHAPE = "UZ-UUIDV7-009";
pub const ERR_UUIDV7_BACKFILL_CONFLICT = "UZ-UUIDV7-010";
pub const ERR_UUIDV7_ROLLBACK_BLOCKED = "UZ-UUIDV7-011";
pub const ERR_UUIDV7_ERROR_RESPONSE_LINKING = "UZ-UUIDV7-012";

pub const ERR_INTERNAL_DB_UNAVAILABLE = "UZ-INTERNAL-001";
pub const ERR_INTERNAL_DB_QUERY = "UZ-INTERNAL-002";
pub const ERR_INTERNAL_OPERATION_FAILED = "UZ-INTERNAL-003";

pub const ERR_INVALID_REQUEST = "UZ-REQ-001";
pub const ERR_PAYLOAD_TOO_LARGE = "UZ-REQ-002";
pub const ERR_FORBIDDEN = "UZ-AUTH-001";
pub const ERR_UNAUTHORIZED = "UZ-AUTH-002";
pub const ERR_TOKEN_EXPIRED = "UZ-AUTH-003";
pub const ERR_AUTH_UNAVAILABLE = "UZ-AUTH-004";
pub const ERR_SESSION_NOT_FOUND = "UZ-AUTH-005";
pub const ERR_SESSION_EXPIRED = "UZ-AUTH-006";
pub const ERR_SESSION_ALREADY_COMPLETE = "UZ-AUTH-007";
pub const ERR_SESSION_LIMIT = "UZ-AUTH-008";

pub const ERR_API_SATURATED = "UZ-API-001";
pub const ERR_QUEUE_UNAVAILABLE = "UZ-API-002";
pub const ERR_WORKSPACE_NOT_FOUND = "UZ-WORKSPACE-001";
pub const ERR_WORKSPACE_PAUSED = "UZ-WORKSPACE-002";
pub const ERR_WORKSPACE_FREE_LIMIT = "UZ-WORKSPACE-003";
pub const ERR_BILLING_INVALID_SUBSCRIPTION_ID = "UZ-BILLING-001";
pub const ERR_BILLING_STATE_MISSING = "UZ-BILLING-002";
pub const ERR_BILLING_STATE_INVALID = "UZ-BILLING-003";
pub const ERR_BILLING_INVALID_EVENT = "UZ-BILLING-004";
pub const ERR_CREDIT_EXHAUSTED = "UZ-BILLING-005";
pub const ERR_SCORING_CONTEXT_TOKENS_INVALID = "UZ-SCORING-001";
pub const ERR_ENTITLEMENT_UNAVAILABLE = "UZ-ENTL-001";
pub const ERR_ENTITLEMENT_PROFILE_LIMIT = "UZ-ENTL-002";
pub const ERR_ENTITLEMENT_STAGE_LIMIT = "UZ-ENTL-003";
pub const ERR_ENTITLEMENT_SKILL_NOT_ALLOWED = "UZ-ENTL-004";
pub const ERR_SPEC_NOT_FOUND = "UZ-SPEC-001";
pub const ERR_RUN_NOT_FOUND = "UZ-RUN-001";
pub const ERR_INVALID_STATE_TRANSITION = "UZ-RUN-002";
pub const ERR_AGENT_NOT_FOUND = "UZ-AGENT-001";
pub const ERR_AGENT_SCORES_UNAVAILABLE = "UZ-AGENT-002";
pub const ERR_PROFILE_NOT_FOUND = "UZ-PROFILE-001";
pub const ERR_PROFILE_INVALID = "UZ-PROFILE-002";
pub const ERR_PROPOSAL_INVALID_JSON = "UZ-PROPOSAL-001";
pub const ERR_PROPOSAL_NOT_ARRAY = "UZ-PROPOSAL-002";
pub const ERR_PROPOSAL_CHANGE_NOT_OBJECT = "UZ-PROPOSAL-003";
pub const ERR_PROPOSAL_MISSING_TARGET_FIELD = "UZ-PROPOSAL-004";
pub const ERR_PROPOSAL_UNSUPPORTED_TARGET_FIELD = "UZ-PROPOSAL-005";
pub const ERR_PROPOSAL_MISSING_STAGE_ID = "UZ-PROPOSAL-006";
pub const ERR_PROPOSAL_MISSING_ROLE = "UZ-PROPOSAL-007";
pub const ERR_PROPOSAL_MISSING_INSERT_BEFORE_STAGE_ID = "UZ-PROPOSAL-008";
pub const ERR_PROPOSAL_DISALLOWED_FIELD = "UZ-PROPOSAL-009";
pub const ERR_PROPOSAL_UNREGISTERED_AGENT_REF = "UZ-PROPOSAL-010";
pub const ERR_PROPOSAL_INVALID_SKILL_REF = "UZ-PROPOSAL-011";
pub const ERR_PROPOSAL_UNKNOWN_STAGE_REF = "UZ-PROPOSAL-012";
pub const ERR_PROPOSAL_DUPLICATE_STAGE_REF = "UZ-PROPOSAL-013";
pub const ERR_PROPOSAL_WOULD_NOT_COMPILE = "UZ-PROPOSAL-014";
pub const ERR_PROPOSAL_NO_VALID_TEMPLATE = "UZ-PROPOSAL-015";
pub const ERR_PROPOSAL_GENERATION_FAILED = "UZ-PROPOSAL-016";
pub const ERR_PROPOSAL_NOT_FOUND = "UZ-PROPOSAL-017";
pub const ERR_HARNESS_CHANGE_NOT_FOUND = "UZ-HARNESS-001";

pub const ERR_STARTUP_ENV_CHECK = "UZ-STARTUP-001";
pub const ERR_STARTUP_CONFIG_LOAD = "UZ-STARTUP-002";
pub const ERR_STARTUP_DB_CONNECT = "UZ-STARTUP-003";
pub const ERR_STARTUP_REDIS_CONNECT = "UZ-STARTUP-004";
pub const ERR_STARTUP_MIGRATION_CHECK = "UZ-STARTUP-005";
pub const ERR_STARTUP_OIDC_INIT = "UZ-STARTUP-006";
pub const ERR_SANDBOX_BACKEND_UNAVAILABLE = "UZ-SANDBOX-001";
pub const ERR_SANDBOX_KILL_SWITCH_TRIGGERED = "UZ-SANDBOX-002";
pub const ERR_SANDBOX_COMMAND_BLOCKED = "UZ-SANDBOX-003";

pub const ERR_EXEC_SESSION_CREATE_FAILED = "UZ-EXEC-001";
pub const ERR_EXEC_STAGE_START_FAILED = "UZ-EXEC-002";
pub const ERR_EXEC_TIMEOUT_KILL = "UZ-EXEC-003";
pub const ERR_EXEC_OOM_KILL = "UZ-EXEC-004";
pub const ERR_EXEC_RESOURCE_KILL = "UZ-EXEC-005";
pub const ERR_EXEC_TRANSPORT_LOSS = "UZ-EXEC-006";
pub const ERR_EXEC_LEASE_EXPIRED = "UZ-EXEC-007";
pub const ERR_EXEC_POLICY_DENY = "UZ-EXEC-008";
pub const ERR_EXEC_STARTUP_POSTURE = "UZ-EXEC-009";
pub const ERR_EXEC_CRASH = "UZ-EXEC-010";
pub const ERR_EXEC_LANDLOCK_DENY = "UZ-EXEC-011";

pub fn docsRef(code: []const u8) struct { base: []const u8, code: []const u8 } {
    return .{
        .base = ERROR_DOCS_BASE,
        .code = code,
    };
}

test "docsRef returns single base and code tuple" {
    const ref = docsRef(ERR_UUIDV7_INVALID_ID_SHAPE);
    try std.testing.expectEqualStrings(ERROR_DOCS_BASE, ref.base);
    try std.testing.expectEqualStrings("UZ-UUIDV7-009", ref.code);
}
