-- W3C Trace Context correlation for distributed tracing.
-- trace_id is 32 hex chars (16 bytes); stored as text for query/log interop.
-- Canonicalized into schema/001_initial.sql for clean-state installs.
